package com.uit.cloud.kubernetes;

/*
 * Copyright (2019, ) Institute of Software, Chinese Academy of Sciences
 */

import com.github.kubesys.kubernetes.ExtendedKubernetesClient;
import com.github.kubesys.kubernetes.api.model.VirtualMachine;
import com.github.kubesys.kubernetes.api.model.VirtualMachineDisk;
import com.github.kubesys.kubernetes.api.model.VirtualMachineDiskImage;
import com.github.kubesys.kubernetes.api.model.VirtualMachineImage;
import com.github.kubesys.kubernetes.api.model.VirtualMachineNetwork;
import com.github.kubesys.kubernetes.api.model.VirtualMachinePool;

import io.fabric8.kubernetes.client.Config;
import io.fabric8.kubernetes.client.ConfigBuilder;

/**
 * @author wuheng@otcaix.iscas.ac.cn
 * @author wuyuewen@otcaix.iscas.ac.cn
 * @author liuhe@otcaix.iscas.ac.cn
 *
 * @version 1.3.0
 * @since   2019/9/3
 *
 */
public class AbstractTest {

    public static Config config = new ConfigBuilder()
            .withApiVersion("v1")
			.withCaCertData("LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNU1UQXdNVEE1TURNME9Wb1hEVEk1TURreU9EQTVNRE0wT1Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTnVGCi9JaWVFQVhrbU1OV01MTnRuTFdqc2h2c1RnenEyNzB1cHNoK0Z5Rm9LbEVoS3kya1h0Mmx2eklURTR0NTN5bkUKSVVVQ3ljampYd1BPamlVM29penBHYWpxRzF6bTNmY0taZ0tyTGNIUnhEVHFsVnRQdmViNEIvTW41ZUIzTE5NNgpDSkdrbGVkbkZBYmJZODNYTzJJMUdWVzNsV2w2YjNLOThMMHEyZ1QwK3JxaENUVzF4OU9iUXd1cTVsaEU4RDF3CjdUUTBVQVlJb0FmMDNGU2tucDRKa1RuN1pXdXNBZ3QzbjJxT2JtdnBBOFI4OWxZNm5iUGxZbWZhRlA1VGNnTSsKbTlTWCtxWWVGaTY0RmJNZ0R3UzFuR2NQMWl2TDdoeWpqZEo2R2VnTE1MOWlCUVJoQ1NEaVRZVE12RGdvbEJsawpsUUtJeHllTDBXQnhNa1MrWE5FQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFKMUFoeGR6QWVLejVqU285cko0ckJEL3ZsMEoKdGhRN1NXWFRZVGZPa0svY3BWR1dhZ2FxM1h6djIzRHRiZXNKMmd0bnR3TUtYd0czWkdOanJRK21acmdqOFg0VgpFTFpaMko3QVVLY2pyMkhueC9qZVQ1QXlPMHRWbWxuZlhqTjJvckIxdlplbEEyN0VrWDgwM3R4cU15N2dodFlBClVxbWh5V2l1bTAwSWhWUkducWF1QjAvcThCb2J5UElvTnU5TXptUXB5ZkhEeElYYi9iUEpXdDE4MW5nakxhNU0Kd1ZwZmRjdzgwTDR1RWVpZU0wcUtidXZxb0JXNFVxZXBBRnJTVnpjNFRkNmhoZm9uQVN2bmhoU0R5Rld0L0k5ZwpqaVIwS0tSZ1lLRFlnT0VQcE9ieGt1azFIQkVpNlRoOE5zcGFuZGFNVUZQN3Jha2RtU01OZGN0TUY5MD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=")
			.withClientCertData("LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4akNDQWRxZ0F3SUJBZ0lJU1ZIUWN0enJiNjh3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB4T1RFd01ERXdPVEF6TkRsYUZ3MHlNREE1TXpBd09UQXpOVEJhTURReApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKek1Sa3dGd1lEVlFRREV4QnJkV0psY201bGRHVnpMV0ZrCmJXbHVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXhRV1BTbnBma2IzeUQ3c1YKRWNsMEV6VDQrc2t6V2xTeUZBaVZpcXNJQis3VzhIWXJLMW1oYkpVVGN6S25SMk1WOEdpSDVsWFFic0JCS3NDWApNSWZ0ODg5NmYvT1Eyc3htYWFtSS85QjFGcTk2L2wvdlA2V3Fmc2h3eFNKTjRTNm5ZSFF2ZElkTXFzRGQvazNXCmFxelVGc2ViamdSNmFWbTg4UUxIYkp6Vy9haTZOYkxYN0Z5bFBHNWRTaW5kMDBjQ1RSVyswcXY1R3ZTd2RXb2YKc2I2bFZFQjNJY2hmck1oalFVNUVWS0RnajMxdTRPc1RVeVZPYktqRTJqSlFPbjdMMEdmVSsrTW1BdXd0SmR4OQpValBHNWlyd2V3cVNQVDBxRUJSVUw2enRTTUdUVUZINWc4eHB0S0M5TlMxNXlNNXZqdjZFdHZPaXA5aDd1L1Q1CkNRczQ5d0lEQVFBQm95Y3dKVEFPQmdOVkhROEJBZjhFQkFNQ0JhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFKcTJXOVA4emkreUpIZXhOTEs1cnZseUVJcGthZEN4RG9ReQpEdEJ6SjFIN2FpMFkrbTBsZUhqMXVXbCtyQmRlYXlhUENNNW9sRjdLVlc3cDRGdUMzNlo0VEFkZlk1ZG9tSDVwCldpZ2hXaGhTbzhFWkZGMVJudC9UNTJuSkxjcVdsbS9wUVNoV2p4OVJPNE5tVU1qY09yYU5sQXpPNjQycUtsT20KUHpIMUlabDFaU3RjOFI4RWdmRWVjMkExOERXYVdPa3VZMlFnb0FNMlNGMVFvRVhRc0N5NWU1bFNCcW1xQUVyZAo5UEdERGRkaFNTbFhJQUxkSVVlZWdXZDBZdWJsb2pjTG9aZXQwam1LendISWljMEcybG9IVVdKbzlqS1BFQzdjCmxmM0lmeVd6b3c3Q1ZqN0FuNlgzOXc3UW9WZXNZMHM4SmgyOUNXUG8rUnh3QWp0eUROYz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=")
			.withClientKeyData("LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBeFFXUFNucGZrYjN5RDdzVkVjbDBFelQ0K3NreldsU3lGQWlWaXFzSUIrN1c4SFlyCksxbWhiSlVUY3pLblIyTVY4R2lINWxYUWJzQkJLc0NYTUlmdDg4OTZmL09RMnN4bWFhbUkvOUIxRnE5Ni9sL3YKUDZXcWZzaHd4U0pONFM2bllIUXZkSWRNcXNEZC9rM1dhcXpVRnNlYmpnUjZhVm04OFFMSGJKelcvYWk2TmJMWAo3RnlsUEc1ZFNpbmQwMGNDVFJXKzBxdjVHdlN3ZFdvZnNiNmxWRUIzSWNoZnJNaGpRVTVFVktEZ2ozMXU0T3NUClV5Vk9iS2pFMmpKUU9uN0wwR2ZVKytNbUF1d3RKZHg5VWpQRzVpcndld3FTUFQwcUVCUlVMNnp0U01HVFVGSDUKZzh4cHRLQzlOUzE1eU01dmp2NkV0dk9pcDloN3UvVDVDUXM0OXdJREFRQUJBb0lCQVFDMTF3N01WNnV6TU5Pagp6ekNBRFNYVHdGVjM2WkU2OHVhMDlNTklpOWhLc2hheE11OWZBRWVybHQrdnQvV0tQcHAyRzVRcWM5Ti9GSFJSCkNCWENsZ0o1djJtNWhFeVNsSXFGUlJNTHdCTUJVQTY5amorYng4UlhaWm9uYUNUbkM0OHh4Nm93Njl0SDBlQlMKSVBjZjE4bWNDTGk2VjhtL1NETEpZcDQ2MFhyZisyWER0TmtaYVF4Z21EayticWtoL2htVFBGcmhCMlNXc1djVApXS2J3VUYrSnA3dDh4d3Y3RlozQ3kwdzI4MFFzZHlMZTFOZ3dZQTFwdHBFRjJUTFArTEROWTFHUW9rYitoRFM0CjkwdkxsSmplZFlKNGpCblAyclJpaTBwNFJ2SmVvcnNQNGJGRWRBVWlwQWJPY1ZXS3poUGtyVlA4RUVyWW40enAKYVg1WUh1TjVBb0dCQU5CNFhTb2Fzb3daU0VUcWRPVmxwNjZsV2tlczAveUhLM2gvUlRPbjV1dlYveFlhcEVyTgpGSC9McDhEMDlvL2hrOS9rYzQvOXBRQW1CcGF3K2NBZHZueVFTRTRNSXAxMmRFQVc5bEJMYkRKNkRXRUhCZi9kCkF1c2xBRmxSdm5KeHJxUnJPZjBJVG5CYmIraGlack1LWW12ZFUyeGlnN1lFWEUxcnVPQ0UyK0UxQW9HQkFQSHcKL2VGa2xJUzl2WEdHV0JnWWlnY0JycFR1NkRnYjBSMzR6ODREdWNUVjdrMWtYQkZQUnRPZjcyeFlPUXluak1OOAorbUZkVUNKcjhoaVREODJPYTZzaEpHQ2xvTVJvUGtTblY4QkU2OGYxZjhBWE9ORjBXWmtGOEF3cm9wVlBrRFBYClI4eFBRQi90YVBJWnV3cEtmZkt4b0FVL3VBYkdCT0w2ZHhZNFJ3TDdBb0dBSGpHUXJNeDVGN21Cc2htVEhMYUEKZHRjVUlGVnp6cHQxUEZxU2wweTJNV29wSy9abjNUMmV2bk9zdEZIR2RFaGp0b1hNQndyaG53Zmk1R2gxZzlITApDUmVNb1dFNGtqM1owSDZDNWxaR01YbGovcTJadk5reDF3VGc3QTdlMm95RWt1UEUzbFVacDBSWERQMVRpcEx5CmRsVDBCRHF3Z09oWXhnM1lGUXlwSEJFQ2dZRUF1UUEvRWRkNEhaeDh2TTh1azVaSURSMkRJbzBnY3E4S2szR0wKYlF1NlJFSVZpNFkvUkZrclhtMEFoZ2RiOEVvNlA4MVVJNWxYeWtwaWY5b01EbkZsOFNCUmtibDBtbHJmcWwyUApvd3pRZ2tFK0kyTmVaZ01pOC9qdldrOFBiajY5bEhaOGgwVGVVc3VXSVBIOTdOdVRQVDRIajV2dW12ZFdDejNjClM5aFNySHNDZ1lBdWlhWmY3ajVvZDA5aVZXcUhhVjREdEJWbWhNTnZtemN3NlBqRVJyampUeU5ibERYbWlzdTQKUzNFc05mRFNKZy9Sdmc0L055aGEyYjhGVUpHNDdjZ21lRkREdHBoWlJINDBqeGQ0SFEzOFRwaVg5TVZTOGZGcgpuV0tTWnhUUGh1dk1ibHRseTVvOGRKS0RiVHZ0SGIxYndnalZTTFFVOUFFTi9oc1NldkZyeGc9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=")
			.withMasterUrl("https://192.168.1.200:6443")
            .build();

    public static ExtendedKubernetesClient getClient() throws Exception {
        return new ExtendedKubernetesClient(config);
    }

    public static VirtualMachine getVMByName(String name) throws Exception {
        return getClient().virtualMachines().get(name);
    }

    public static VirtualMachineImage getVMImageByName(String name) throws Exception {
        return getClient().virtualMachineImages().get(name);
    }

    public static VirtualMachineDisk getVMDiskByName(String name) throws Exception {
        return getClient().virtualMachineDisks().get(name);
    }

    public static VirtualMachinePool getVMPoolByName(String name) throws Exception {
        return getClient().virtualMachinePools().get(name);
    }

    public static VirtualMachineDiskImage getVMDiskImageByName(String name) throws Exception {
        return getClient().virtualMachineDiskImages().get(name);
    }

    public static VirtualMachineNetwork getVMNetworkByName(String name) throws Exception {
        return getClient().virtualMachineNetworks().get(name);
    }
}
